<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    const p1 = new Promise(function (resolve, reject) {
        setTimeout(function () {
            //reject(new Error("fail"));
            resolve(-99);
        }, 300)
    })
    const p2 = new Promise(function (resolve, reject) {
        setTimeout(
                () => resolve(100),
                16);
        //p1的状态就会传递给p2，p1的状态决定了p2的状态，3000ms后（并非100ms）才执行p2
        //setTimeout(() =>resolve("p2"),100); //此时p2的状态 自行决定，100ms后即执行
    })


    p2
     .then(function(result){
         console.log(result);
     }).catch(function(err){
        console.log(error);
    });


    /*
     p2 中定时器延迟时间 < p1 定时器中延迟时间，输出：
     Error: fail at promise9.html:11
     */

    /*
     p2 中定时器延迟时间 > p1 定时器中延迟时间，输出：
     Uncaught (in promise) Error: fail at promise9.html:11
     Error: fail  at promise9.html:11
     */
</script>
</body>
</html>